# Generated by Django 4.2.1 on 2023-05-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
